### ISSUE TITLE
WebAssembly?

### ISSUE THREAD

**Issue by cherue** [kaitai-io/kaitai_compress#1]
All sorts of languages can already compile to [WebAssembly](https://github.com/appcypher/awesome-wasm-langs), there are several efforts to write standalone VMs ([awesome-wasm#non-web-embeddings](https://github.com/mbasso/awesome-wasm#non-web-embeddings), [life](https://github.com/perlin-network/life), and others) and it is already possible to run WebAssembly through node ([wast example](https://gist.github.com/kanaka/3c9caf38bc4da2ecec38f41ba24b77df), can easily be modified to run wasm, too).

So how about implementing all the pre-processors in WebAssembly and just having a wrapper for each language? This would make it so the pre-processors only have to be implemented once (especially useful for stuff like [LZHAM](https://github.com/richgel999/lzham_codec) with C++ source only). Thoughts?

**Comment by KOLANICH** [comment]
>So how about implementing all the pre-processors in WebAssembly and just having a wrapper for each language?

I don't think it is a good idea.
1. The drawbacks of using wasm assemblies run interpreters are 
* these interpreters are non-standard dependencies
* they are not native for the languages, they are virtual machines, so some overhead calling the interpreted functions from native ones and back.
2. even if there was a way to transform wasm into llvm bytecode, then compile and link, there is no purpose to do that. These kind of libs is usually written in native languages like C, C++ and rust and the wrappers for popular languages are already created by the enthusiasts. When one wants to create a new lib, he doesn't write it in wasm, instead he writes it in a native language.
3. Is not the approach taken here. KS prefer to create the code as if it was created by a human. I mean a human won't use these wasm ports of compression algorithms run in the interpreters you have meant. Instead he just take the existing widely used libs. So KS runtimes are meant to use the libs which are de-facto standards in the communities around the corresponding languages.

**Comment by KOLANICH** [comment]
You may want to create compressors for JS in WASM, but for other languages it makes no sense. IMHO compressors for JS in wasm make little sense too, they should be a part of a browser, even if actually implemented in wasm.

**Comment by cherue** [comment]
> 1. The drawbacks of using wasm assemblies run interpreters are
>    
>    * these interpreters are non-standard dependencies
>    * they are not native for the languages, they are virtual machines, so some overhead calling the interpreted functions from native ones and back.

This could be solved by not including the wasm pre-processors but requiring explicit inclusion. A flag in the compiler maybe. This makes it so a user can be aware of the trade-offs you mentioned.

> 2. even if there was a way to transform wasm into llvm bytecode, then compile and link, there is no purpose to do that. These kind of libs is usually written in native languages like C, C++ and rust and the wrappers for popular languages are already created by the enthusiasts. When one wants to create a new lib, he doesn't write it in wasm, instead he writes it in a native language.

There is no transformation intended. The point is that WebAssembly compiles most languages, so if there isn't already a wrapper for something it can be implemented once (like compiling LZHAM to wasm) and then it can be used by all languages that have a kaitai compatible wasm wrapper (which would only need to be setup once).

> 3. Is not the approach taken here. KS prefer to create the code as if it was created by a human. I mean a human won't use these wasm ports of compression algorithms run in the interpreters you have meant. Instead he just take the existing widely used libs. So KS runtimes are meant to use the libs which are de-facto standards in the communities around the corresponding languages.

I hadn't considered that human readable code is the goal. But how much more readable is using an existing library? With Python you end up with some C code sooner or later anyways. Might as well end up with C code compiled into wasm.

Also there are a bunch of compression/encryption/obfuscation algorithms that don't have existing implementations in many languages. Sometimes people even roll their own. I think wasm is a great way to get a cross-platform/cross-language implementation for at least these cases.

**Comment by KOLANICH** [comment]
>The point is that WebAssembly compiles most languages, so if there isn't already a wrapper for something it can be implemented once (like compiling LZHAM to wasm) and then it can be used by all languages that have a kaitai compatible wasm wrapper (which would only need to be setup once).

Why one needs to compile into a wasm and create a wrapper for a wasm-compiled lib, if he can compile to a native lib and create a wrapper for it, and in most cases he doesn't need to even do it - there are wrappers already created.

>Also there are a bunch of compression/encryption/obfuscation algorithms that don't have existing implementations in many languages.

Then they need to be implemented in a low level language.

I think wasm is a great way to get a cross-platform/cross-language implementation for at least these cases.

Yes, wasm is a way for a cross-language impl ... if one has to use that impl. For example the impl may be proprietary closed-source, in that case its spreading benefits only its vendor, IMHO the best way to deal with such impls is don't use them at all in production and to create an own free ones. IMHO there is no specific reasons to support wasm libs directly in KS runtime. Instead one needs the way to transform wasm libs into native libs.

**Comment by cherue** [comment]
> IMHO there is no specific reasons to support wasm libs directly in KS runtime.

The least intrusive way would be to make a separate project that has wrappers for all target languages  plus pre-processors in compiled and source form. That way people can use them after some initial setup.

I still think it would be nice to just be able to drop in a wasm blob and kaitai automagically knowing what to do with it but maybe WebAssembly needs to mature more for that to be a good idea.

**Comment by KOLANICH** [comment]
>just be able to drop in a wasm blob

In fact it may be a good idea to have a stable ABI. I mean not only a wasm blob, but any binary with the defined interface. I guess a function to introspection (returns count of variables needed to create a context and their sizes), functions for lib init and shutdown, a function to create a context, a function accepting the context and data.

Again, I don't think that supporting wasm directly is a good idea. IMHO a wasm module should be converted into a native lib somehow, I guess with a llvm frontend.

**Comment by cherue** [comment]
> Again, I don't think that supporting wasm directly is a good idea. IMHO a wasm module should be converted into a native lib somehow, I guess with an llvm frontend.

I don't understand why you would want to do that? What speaks against just using wasm?

BTW the inspiration for my proposal is [this talk](https://www.youtube.com/watch?v=u2kKxmb9BWs&feature=youtu.be&t=1296) with a game written in Rust being controlled by an AI written in C with glue code in Python. That made me think of the possibility of implementing whatever pre-processor you might want in whatever language that compiles to WebAssembly and then using that from any of the languages that kaitai compiles to.

**Comment by GreyCat** [comment]
@cherue, there are many different "cross-language" transpiling / VMs initiatives, WebAssembly is one of them. It's one of the methods to solve this problem, with it's own set of pros and cons. @KOLANICH has do a good job outlining most of them.

It's nothing wrong with implementing WebAssembly-based approach too — if it will get traction, it would be very easy to get some extra syntax sugar for it in KSYs. You're most welcome to contribute any work towards that, or start a more concrete discussion if you want anything done in ksc / language.

**Comment by KOLANICH** [comment]
>BTW the inspiration for my proposal is this talk with a game written in Rust being controlled by an AI written in C with glue code in Python. That made me think of the possibility of implementing whatever pre-processor you might want in whatever language that compiles to WebAssembly and then using that from any of the languages that kaitai compiles to.

You definitely need to look at MS .Net (including https://github.com/RyanLamansky/dotnet-webassembly ) and Oracle GraalVM (in fact it is something like .Net, but for JVM + modules for python (unusable in its current state), node and llvm).

**Comment by cherue** [comment]
@GreyCat Glad to hear you're open to that, but it seems it might be a while before that can happen.

@KOLANICH .Net seems limited but GraalVM looks promising. It's especially cool that it can be used right now. I'll look into implementing that: a GraalVM host that can be interacted with that takes care of processing data. The only downside is that LLVM bitcode is platform dependent, but I think Travis supports all major platforms, so that's not a real problem.

**Comment by cherue** [comment]
Also my question has been answered so I'm closing this. Thanks!
